### ISSUE TITLE
Separate concerns between runtime spec and distribution

### ISSUE THREAD

**Issue by simonferquel** [cnabio/cnab-spec#161]
In its original design, bundle.json (and bundle.cnab at this time) was supposed to be both the format the runtime would work with, and the distribution format. It lead to a mix of concerns between runtime (parameters declaration, image locations etc.) and distribution concerns (immutability, content validation etc.).

This has changed and now bundle.json (should) purely describe runtime interactions, while distribution should be handled externally (cnab-to-oci for container-based CNABs, still unclear for VM-based ones). 
However, there are still some mixing of concerns in the current state of the spec, and I think it is mainly due to the orignal design heritage:
- Content validation and immutability still surface in the following ways:
  - the content-digest field on images / invocation-images
  - the "at-rest" requirements for having digested references or content-digest for all images / invocation-images
- Thick bundles:
  - this should be a distribution concern, and should not be mixed with the runtime specification
  - for cnab-to-oci, this could be handled by producing exports of the root OCI index with all its referenced manifests and blobs. Such an export is easily importable in an air-gapped cluster, as soon as a registry is part of the infrastructure. For more restrictive air-gapped scenarios, directly ingesting those OCI exports using containerd or docker APIs is easily doable.

I think we should aim to do something similar to what OCI has done for containers: there is a runtime spec that describes how container runtimes should be able to run a container, and there is a separate distribution spec explaining how content-addressed blobs and manifests can guarantee immutability, integrity etc. On top of that, there is TUF that can be leveraged to add content-trust, proof of origin etc.

My suggestion is then:
- drop all things in the spec related to digests, immutability, thick bundles (actually, everything related to distribution)
- spin-up a second spec related to cnab distribution, based on the work already done with cnab-to-oci (we can promote cnab-to-oci as the reference implementation of this spec, a bit like duffle is the reference implementation of the runtime spec)
- start a discussion about non-container CNAB distribution. I have the feeling we can leverage OCI registries for that as well (using ORAS for storing VMs, and referencing the ORAS manifests in cnab-to-oci).

@technosophos @radu-matei @michelleN @silvin-lubecki @chris-crone, @glyn, I would really like your input on that.

**Comment by glyn** [comment]
I think bundle.json/bundle.cnab needs to include content digests so that the runtime and invocation images are certain to be operating on the same images used when constructing the bundle.

In the Pivotal Function Service image relocation use case which I've described before, the invocation image needs to know the original image names as well as the relocated image names so that we can map kubernetes configuration files correctly. Precisely how this information is passed to the invocation image is less crucial. I'd be happy for bundle.json/bundle.cnab to be immutable after bundle construction and capture the original->relocated image name correspondence separately.

**Comment by technosophos** [comment]
Can we close this one?
