### ISSUE TITLE
CNAB Spec patterns are not RE2

### ISSUE THREAD

**Issue by astrieanna** [cnabio/cnab-spec#215]
The [pattern for credential paths](https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L19) and the [pattern for parameter paths](https://github.com/deislabs/cnab-spec/blob/master/schema/bundle.schema.json#L184) in `bundle.scheme.json` both use the `?!` lookahead feature that is allowed by jsonspec but is not available in Go's re2 regexes. Javascript and PCRE regexes support `?!`, but re2 has consistently responded to issues with no plans to do so.

Unfortunately, there is no obvious way to exclude a prefix that's more than one character long without using `?!`. In re2, the easiest thing would be to mark the pattern as a negative pattern -- "must not match" rather than the usual "must match". However, since javascript supports `?!`, it seems unlikely that jsonspec would want to add extra fields to support re2 implementation constraints.

It is valuable to have these checks in the json schema rather than just in markdown prose, but our golang implementation can't handle the patterns because they include `?!`.

cc @ryanmoran

**Comment by technosophos** [comment]
Given that this is the spec repo... on the spec side we could merely drop the regex, or we can keep it and let the Go-based projects solve this problem on their own. I think I would be in favor of the second approach.

For Duffle/cnab-go, I guess the question is: Is there a PCRE implementation in Go? I guess we could use `cgo` to link it in... but that seems like a heavy-handed approach.

**Comment by silvin-lubecki** [comment]
We have the same issue here on docker app. We can't use the json schema provided by the specs to validate the bundles, as AFAIK there's no ECMA-262 compatible regexp implementation in Go, and all the json schema implementations in Go use the regexp package provided by Go.
So even just parsing the schema is not possible... I'd be more in favor with removing it from the schema and add a proper validation in the cnab-go library.

**Comment by technosophos** [comment]
If anyone is interested in replacing this, can you create a PR? If it can be done without breaking any existing CNAB modules, we can include it in CNAB Core 1.1.0

**Comment by vdice** [comment]
Closed by https://github.com/cnabio/cnab-spec/pull/330
