### ISSUE TITLE
When is a claim result updated?

### ISSUE THREAD

**Issue by itowlson** [cnabio/cnab-spec#251]
The Claims spec (https://github.com/deislabs/cnab-spec/blob/master/400-claims.md) has this to say about the `result` attribute:  `result: The outcome of the bundle's last action`.  Additionally, the `result` contains a `status` which gives 'the status of the last phase transition' - this is an outcome such as `success` or `failure`.  Together these strongly imply that the result (and presumably other parts of the claim such as the `parameters` section) is updated when an action _completes_, i.e. the invocation container _exits_.  And indeed the spec says "The result object is populated by the result of the invocation image's action."

However, `result.action` is documented as "the action that the current bundle is in."  This strongly implies that if an action is in progress then it reflects _that_ action, not the last.

Is this just a wording glitch describing `result.action`?  And the claim is not updated at the beginning of an action, and does not indicate if an action is in progress?

**Comment by carolynvs** [comment]
As a related question, I've had actions fail in the middle of an operation (maybe someone CTRL-C'd out of it, or there was some fatal panic that prevented the claim from being written). It's not clear to me if I can/should be updating the claim at the beginning of the operation to indicate that the tool is initiating the op, so that we don't lose information for example that "upgrade was started"? It would also give me a way to see that the op is in progress from the claim.

Or are tools expected to only update the claim once the op is completed, successfully or otherwise?

**Comment by technosophos** [comment]
@itowlson I believe the description of `result.action` is incorrect. It should probably be `the name of the action that last caused this claim to be updated` (which is a nice succinct way of working around the fact that some actions do not alter the claim, like stateless actions.

@carolynvs ideally, the runtime would create a claim for a failed action (at least, this is what we did in Helm, and it has some big advantages). So we would have to trap failures and perform this operation. In Helm, we updated the "release" (the Helm equiv of a claim) three times during an action (pre-install, in-progress, post-install). We _could_ do this if we think it is advantageous.

**Comment by carolynvs** [comment]
I see two areas of improvement for later:

1. Providing a way to indicate on a claim that an action has begun. Consider the prototype CNAB Dashboard I showed a while back. If we updated the claim when an action has started, you could know which bundles are being currently executed, and which action. Right now claims are stored on the local file system so it may not make sense, but if you think about in the future when teams may have claims persisted in a common location, and are reporting off of that claim store... That's where this would be useful.
2. Right now duffle is only handling the returned error from an action's execution and then updating the claim. There are edge cases where the claim may never be updated even though an action was executed to some point of failure, for instance the power went out, code panic, CTRL+C caused tool to quit immediately, acts of godzilla, etc. I can see having some record of the attempt being useful. That way we at least know that resources are in an uncertain state, and the bundle needs to be retried/cleaned up.
