### ISSUE TITLE
Clarify character set constraints on name (Add a link to the Unicode spec)

### ISSUE THREAD

**Issue by ndeloof** [cnabio/cnab-spec#273]
spec says
>  name MUST contain only characters from the Unicode graphic characters
    The Unicode graphic character set allowed for name includes letters, numbers, punctuation, symbols, and spaces; it does not include newlines or tabs.

I'm not sure this definition is clear enough on supported characters. Typically, what does _symbols_ mean ? Can I use Klingon characters? emojis?  Unicode Character 'BACKSPACE' (U+0008)  etc. 

Maybe clarify using explicit Unicode General categories Letter (L), Number (N) ... and explictely exclude Controls & al (C)

**Comment by technosophos** [comment]
"Unicode Graphics Characters" is a defined set of Unicode characters. 

> In Unicode, Graphic characters are those with General Category Letter, Mark, Number, Punctuation, Symbol or Zs=space. Other code points (General categories Control, Zl=line separator, Zp=paragraph separator) are Format, Control, Private Use, Surrogate, Noncharacter or Reserved (unassigned)

https://www.unicode.org/versions/Unicode5.2.0/ch02.pdf#G25564

**Comment by technosophos** [comment]
Oops... the link was to the spec, and the quote was from the wikipedia entry on graphic characters.

https://en.wikipedia.org/wiki/Graphic_character

**Comment by ndeloof** [comment]
Oh ok. I googled for it but didn't found anything obvious.
Then a link would avoid stupids like me to make such a mistake ;)

**Comment by technosophos** [comment]
Thanks! I updated the title and will do a PR next week.

**Comment by technosophos** [comment]
The PR was merged a long time ago, so I am closing this issue.
