### ISSUE TITLE
Clarify contentDigest meaning for docker/OCI images

### ISSUE THREAD

**Issue by glyn** [cnabio/cnab-spec#287]
Let's start with some definitions (based on the ["OCI Image Format Specification"](https://github.com/opencontainers/image-spec/blob/master/spec.md)).

Docker and OCI images have two types of digest: a _repo digest_ and an _image id_. A repo digest is the SHA-256 digest of the _compressed_ image manifest. Since compression depends on the implementation of the registry used to store the image, the repo digest doesn't logically exist until the image has been pushed. An image id, on the other hand, is the SHA-256 digest of the _uncompressed_ image configuration, which is independent of the registry implementation.

Both these digests are content addresses of an image in the sense that each uniquely identifies the content (modulo SHA-256 collisions). Note that the [docker registry spec](https://docs.docker.com/registry/spec/api/#content-digests) refers to the repo digest as a "content digest".

The [CNAB spec](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md) defines the `contentDigest` fields in bundle.json as follows, firstly for invocation images:
> The contentDigest field MUST contain a digest, in OCI format, to be used to compute the integrity of the image. The calculation of how the image matches the contentDigest is dependent upon image type. (OCI, for example, uses a Merkle tree while VM images are checksums). During bundle development, it may be ideal to omit the contentDigest field and/or skip validation. Once a bundle is ready to be transmitted as a thick or thin bundle, it must have a contentDigest field. If a contentDigest field is present, a runtime MUST validate the image digest prior to executing an action. If the contentDigest is not present, the runtime SHOULD report an error so the user is aware that there is no contentDigest provided. Runtimes MAY allow users to override this behavior and perform actions on bundles that do not have contentDigest values populated.

and then for images other than invocation images:
> contentDigest: MUST contain a digest of the contents of the image, in OCI format, to be used to compute the integrity of the image. The calculation of how the image matches the contentDigest is dependent upon image type. (OCI, for example, uses a Merkle tree while VM images use checksums.)

Since both repo digests and image ids are roots of Merkle trees, the CNAB spec doesn't actually prescribe whether repo digest or image id (or indeed some other Merkle tree root digest!) should be used for `contentDigest` fields of docker/OCI images. This needs clarifying so that CNAB runtimes know how to validate these fields.

**Comment by trishankatdatadog** [comment]
Great question! I think _image id_ is the better idea, since it's registry-independent... @jlegrone

**Comment by jeremyrickard** [comment]
I think we discussed this way back in 2018 in the early days and this was a common view. I think we ended up going with the assumption it was the repo digest, I’ll see if I can find an old issue in the Duffle repo! 

I think the image id is attractive since it has no registry requirement.

**Comment by jeremyrickard** [comment]
Some of this history was on Docker’s slack I think, so that’s not all going to be recoverable (unless Docker can get it), some related comments and discussion:

https://github.com/cnabio/duffle/pull/691#issuecomment-480893767

**Comment by technosophos** [comment]
I don't think you can reasonably call a hashed file "a root of a merkle tree". That assumes an intent that is clearly not there in VM images (namely, that they are tree-structured).

I am not understanding, though, what particular change you are requesting in the spec. Is it a clarification of which SHA Docker considers to be _the correct_ SHA? Or are you proposing an alternative?

**Comment by glyn** [comment]
> I don't think you can reasonably call a hashed file "a root of a merkle tree". That assumes an intent that is clearly not there in VM images (namely, that they are tree-structured).

This issue is scoped to docker/OCI images.

> I am not understanding, though, what particular change you are requesting in the spec. Is it a clarification of which SHA Docker considers to be _the correct_ SHA? Or are you proposing an alternative?

If I consume a bundle containing a docker/OCI image with contentDigest specified, I need to know whether that's the repo digest or the image id in order to verify it. I'm not asking which one is _correct_ from Docker's perspective: they both have valid uses. It's merely a choice that the CNAB spec. has to make.

Let's take a simple example to make this crystal clear. CNAB runtime A could assume the contentDigest of a docker/OCI image is its repo digest while CNAB runtime B could assume its the image id. If a bundle created by runtime A was consumed by runtime B, then runtime B could say the contentDigest was invalid because it wasn't what runtime B was expecting.

**Comment by vdice** [comment]
With https://github.com/cnabio/cnab-spec/pull/384 merged, I believe we can consider this issue closed.

**Comment by glyn** [comment]
LGTM, thanks.
