### ISSUE TITLE
Document security implications of using multiple servers to host metadata repositories

### ISSUE THREAD

**Issue by glyn** [cnabio/cnab-spec#314]
This relates to CNAB Security 301: Metadata repositories as described in https://github.com/cnabio/cnab-spec/pull/281. See https://github.com/cnabio/cnab-spec/pull/281#discussion_r363237658.

A usecase I have in mind is where a user consumes bundles from multiple vendors who do not share a single, central server. I expect this to be the case if CNAB becomes popular and is adopted by multiple vendors who will not necessarily be able to agree on a central metadata repository.

In particular, it would be good to spell out how to establish trust in a new metadata repository - presumably mainly by reputation and guess-work? I believe there is a weakness of the current approach in the above usecase and it would be good to call that out so that there are no surprises down the line.

**Comment by trishankatdatadog** [comment]
Thanks for filing this issue!

**Comment by technosophos** [comment]
@glyn Are you still working on this?

**Comment by glyn** [comment]
> @glyn Are you still working on this?

Yes, but I'm looking for someone else such as @trishankatdatadog to fix it.

**Comment by trishankatdatadog** [comment]
I can add a quick note
