### ISSUE TITLE
Claims: Outputs should be stored separately

### ISSUE THREAD

**Issue by technosophos** [cnabio/cnab-spec#327]
It was proposed in a comment here https://github.com/cnabio/cnab-spec/pull/309#discussion_r367614692  that outputs should be stored separately from claims.

In that issue, @jlegrone  said:

> In our internal implementation we don't currently store outputs in claims, but plan to allow querying them on demand. This is because the size of outputs is unbounded, and could make it difficult to scale to keeping many claims in memory. We also want to prevent oversending on the network when an output is generated but never read.

> I wonder if it makes sense to have a separate object for a claim result, that includes outputs? Or perhaps we could remove outputs from claims and this could be left as non-normative for now (they could still be included in the custom map).

There was some follow-up discussion, but the issue needs to have a little more of a design to it.

Note that this will probably introduce breaking changes to libcnab-rust and cnab-go.

**Comment by carolynvs** [comment]
We (me, @jlegrone and @radu-matei) kicked off a WG last meeting while @technosophos was sick to hash this and the remaining claim questions out. Please hold off on calling claims done yet. Jacob and I just met tonight and made lots of progress that I will be drafting into PRs tomorrow.

**Comment by vdice** [comment]
This has been done (thank you @carolynvs !!).  Closing! 🎉
