### ISSUE TITLE
Claims: Move 'outputs' into 'results'

### ISSUE THREAD

**Issue by technosophos** [cnabio/cnab-spec#329]
It has been proposed here https://github.com/cnabio/cnab-spec/pull/309#discussion_r365505351 that we move `outputs` into `results`.

@jlegrone says:

>I feel that action makes the most sense as a top-level field on the claim object, while outputs could potentially be moved into result. This has a practical benefit too; when a user invokes an operation against an external API, the server would be able to send back a stream of claim.result type events until execution is complete. 

Note that this will break cnab-go and libcnab-rust, so needs follow up issues if we decide to do it.

Note that this conflicts with #327

**Comment by radu-matei** [comment]
👍
