### ISSUE TITLE
Review CNAB-Sec

### ISSUE THREAD

**Issue by trishankatdatadog** [cnabio/cnab-spec#369]
@radu-matei and I need to review [CNAB-Sec](300-CNAB-security.md) before asking for votes on the next General meeting on June 10th 2020. In particular, we need to make sure we address airgapped scenarios.

TODO (in decreasing order of importance):
- [x] Trishank: [copying between registries](https://github.com/cnabio/cnab-spec/pull/370)
- [x] Trishank & Radu: [draft PR to delegate targets and verify them](https://github.com/cnabio/signy/pull/80)
- [x] Radu: [move 304 to 8xx](https://github.com/cnabio/cnab-spec/pull/375)
- [x] ~Radu: write about registries which support Signy in 304~ (no longer needed because 304 is in 8xx)
- [x] Trishank: insert Figure 1 already!

**Comment by trishankatdatadog** [comment]
[Draft PR](https://github.com/cnabio/signy/pull/80) for the second TODO

**Comment by radu-matei** [comment]
The security spec has now been merged.
