### ISSUE TITLE
Provide a killer example in the intro

### ISSUE THREAD

**Issue by duglin** [cnabio/cnab-spec#40]
As I make my way through the docs/spec, while I think I understand each piece being presented, what's missing for me is a high-level example to make the concepts concrete. For example, what do you think about providing a really simple (yet compelling) use-case that you walk through in an intro section of the 100 doc?  Something that highlights the pain-point that's being addressed. Talk about how people do this today and show how much easier it'll be using the CNAB tool.

For example, one use-case that comes to mind is someone (who is NOT a kube, or containers, expert) wants to demo a kube app. Normally they might first need to download some CLI tools (kubectl, platform specific CLIs, etc...) and then create a cluster, install helm, use helm to install the app, and then finally they can hit the app in a browser. Perhaps show what this would look like using CNAB and how all of the complexities (and knowledge of each tool) is no longer needed - instead it's just `cnab install ....` and bring up a browser.  

You can then break apart the example and show how the CNAB bits map to each of the manual steps the demo runner would normally have done themselves. I think having this mapping would really help people see how this is all about automating, formalizing, what I think a lot of us already do today but instead of each of us creating some sh install script that we hope someone else can run when we try to share it, cnab ensures it.  Do I have that right?

**Comment by technosophos** [comment]
Closed due to inactivity (and much better documentation since this was originally requested)
