### ISSUE TITLE
Inconsistent spelling of canceled state

### ISSUE THREAD

**Issue by carolynvs** [cnabio/cnab-spec#412]
In the spec we consistently use the spelling `cancelled`. However in cnab-go we have been using the alternative spelling `canceled` when we store state on the claim.

We should pick a spelling (british vs american) and use the same one everywhere. I lean towards sticking with `canceled` since that's what is stored in user's data right now, and update the spec to fix the misspelling.

**Comment by carolynvs** [comment]
Sounds like @jlegrone is also using `canceled` so I suggest that we update the spec to use this variation of the word, treating this as a typo. @chris-crone? @technosophos?

**Comment by chris-crone** [comment]
I think we should ideally move to `canceled` (US spelling) as this is more consistent with tooling like [Golang](https://golang.org/pkg/context/#pkg-variables). We should check that we aren't breaking people though.

**Comment by carolynvs** [comment]
Anyone using cnab-go won't be affected by the change (duffle, porter, data dog). I'm not aware of any other implementations right now. I'll ask on our Slack channel.
