### ISSUE TITLE
Common repository for test data

### ISSUE THREAD

**Issue by radu-matei** [cnabio/cnab-spec#90]
As we're starting to have more clients that interact with bundles, it becomes inevitable that all clients will need to have multiple examples for bundles (and parts of bundles), and define corner cases to test - meaning the work is going to be replicated across repositories.

Would it make sense to have a common repository with example bundles and parts of bundles for clients to use as test data? (This way, we also try to make sure clients are up-to-date.)

**Comment by garethr** [comment]
+1 on this idea.
We could have bundles as well as some basic input/output expectations in a machine readable format. I'd certainly adapt the python client to use something like that. I have some fixtures in https://github.com/garethr/pycnab/tree/master/fixtures which I'd replace.

Maybe start with one hello world example and the input/output in a file?

**Comment by radu-matei** [comment]
One aspect I haven't really thought of is how we would import the test data repo into the client repos - we could use git submodules, but maybe directly cloning might prove to be much simpler solution.

Thoughts?

**Comment by technosophos** [comment]
Any update on this?

**Comment by technosophos** [comment]
Closing as wontfix, since nothing has been done in the last year.
